services:
  mysql:
    image: mysql:latest
    command: --max_connections=10000
    environment:
      MYSQL_DATABASE: "${DB_BASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: "mysql"
volumes:
  mysql: null
  redis: null
